### ISSUE TITLE
Missing required key "allPathParameters"

### ISSUE THREAD

**Issue by crashdump** [fern-api/fern-openapi#125]
I am facing the following error with the release 0.0.29-rc0:

```
 services -> service_v1/workflow -> endpoints -> [7]: Missing required key "allPathParameters"
```

I have tried to simplify my configuration as much as I could but that did not help.  Reverting to 0.0.28 solves this.

@dsinghvi for info, given our discussion on #120 (which may or may not be related).

**Comment by dsinghvi** [comment]
@crashdump can you try doing the following: 

1. Run `fern upgrade --rc`
2. Move your definition folder to be directly inside the `fern` folder
3. Move your `generators.yml` to be directly inside the `fern` folder
4. Rerun `fern generate`

**Comment by crashdump** [comment]
@dsinghvi what would that look like in a multi-api environment? My configuration is as follow:

`ls fern/`
`.
├── bar
│   ├── definition
│   │   ├── api.yml
│   │   └── v1
│   │       ├── barz.yml
│   └── generators.yml
├── foo
│   ├── definition
│   │   ├── api.yml
│   │   └── v1
│   │       ├── fooz.yml
│   └── generators.yml
└── fern.config.json`

**Comment by dsinghvi** [comment]
@crashdump There would be an `apis` folder above `bar` and `foo`

**Comment by dsinghvi** [comment]
See here https://github.com/fern-api/fern/tree/main/test-definitions/fern

**Comment by crashdump** [comment]
Thanks @dsinghvi, I can confirm this solves the issue. This may be worth a mention in the contrib docs?
