### ISSUE TITLE
`operationId` renders weirdly in Stoplight

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-openapi#34]
<img width="1302" alt="Screen Shot 2022-12-23 at 6 18 06 PM" src="https://user-images.githubusercontent.com/10870189/209412778-95477148-2fa3-412e-b2a9-b13e1b0ddf69.png">

Stoplight uses the endpoint `operationId` as the title for the endpoint page. However, since fern generates the operation id as `<service name>.<endpoint id>` the page looks awkward. 

It would be better if Stoplight was able to import a fern generated OpenAPI and have a more natural looking title for each endpoint.

**Comment by dsinghvi** [comment]
Stoplight uses the `summary` key under the OpenAPI path as the endpoint page display name. If that doesn't exist it defaults to the display name. So the generator should instead propagate [endpoint display name](https://github.com/fern-api/fern/blob/5eb98338306d72424066068fb84f7d37f6de9f8e/fern/ir-types-v4/definition/services/http.yml#L30) to the `summary` field.
