### ISSUE TITLE
Environment name doesn't populate in Stoplight

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-openapi#37]
The OpenAPI spec that is generated from fern doesn't populate a description for each environment (which stoplight uses). 
```yaml
servers:
  - url: 'https://api.example.com'
```
<img width="930" alt="Screen Shot 2022-12-23 at 6 36 40 PM" src="https://user-images.githubusercontent.com/10870189/209413573-86ee8b05-5d80-47fc-82d3-38bb037e3915.png">
By default there is no name coming through for the environment, so it defaults to `Live Server`. 
<img width="634" alt="Screen Shot 2022-12-23 at 6 37 31 PM" src="https://user-images.githubusercontent.com/10870189/209413601-f1655e0c-e9ff-413d-a691-a52064d7380c.png">

What I would like: 
The spec that fern should generate should look more like: 
```
servers:
  - url: 'https://api.example.com'
    description: Production # comes from environment name
```

We also have `docs` on the environment so its an interesting question of should we plumb the environment docs or name into the OpenAPI environment description.

**Comment by dsinghvi** [comment]
https://github.com/fern-api/fern-openapi/pull/41 fixed with this PR
