### ISSUE TITLE
I want to have more flexibility with my API name in Stoplight

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-openapi#49]
Fern takes the `name` from `api.yml` to populate the `title` field within the generated OpenAPI. In Stoplight, I don't want my API title to be `gigs-core-api`; I want `Gigs Core API`. 

```
openapi: 3.0.1
info:
  title: gigs-core-api
```

**Comment by dsinghvi** [comment]
The title defaults to the `display name` of the api and if not present then uses the `name`. 
https://github.com/fern-api/fern-openapi/blob/7705e19acea5bda15e94f766ca3310bbc0ac3629/src/convertToOpenApi.ts#L46

Example usage: 
https://github.com/fern-mirrorworld/mirrorworld-api/blob/e1448f658939be627754e89b3ceb9de3960b060e/fern/api/definition/api.yml#L1-L2

**Comment by dannysheridan** [comment]
No way! Didn't realize `display-name` was implemented for `api.yml` 🦅
