### ISSUE TITLE
[ReadMe] Endpoint names render oddly

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-openapi#55]
Endpoint names should have a display name when shown to the user.

How Fern-generated ReadMe docs look now:
<img width="1432" alt="Screenshot 2022-12-28 at 2 42 47 PM" src="https://user-images.githubusercontent.com/83524670/209875549-a800ec8e-818b-4c59-8dc6-43d8aabe50a8.png">

How Primer-generated ReadMe docs look now:
<img width="1410" alt="Screenshot 2022-12-28 at 2 43 49 PM" src="https://user-images.githubusercontent.com/83524670/209875613-db3597ab-5b1b-42f4-af37-34aae706f153.png">

**Comment by dsinghvi** [comment]
Do you know what field in the openapi spec readme uses for the title? Would be useful to mess around and get that info

**Comment by dannysheridan** [comment]
Yes. 

https://github.com/fern-primer/primer-openapi/blob/bd5e5d6f56b8e9efa883000ef788600fe5d00ea7/openapi.yml#L357

**Comment by dannysheridan** [comment]
we opted for building Fern Docs instead of provider-specific OpenAPI generator changes.
