### ISSUE TITLE
Generate a `3.1.0` compliant OpenAPI Spec

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern-openapi#65]

**Comment by dannysheridan** [comment]
OpenAPI specification release history:

<img width="519" alt="Screenshot 2023-07-24 at 14 34" src="https://github.com/fern-api/fern-openapi/assets/83524670/7e6dc645-fe97-47e9-ae70-653a49265fbe">

source: https://en.wikipedia.org/wiki/OpenAPI_Specification#Release_dates
